ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS worktree_path TEXT;

ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS base_branch VARCHAR(100)
NOT NULL DEFAULT 'main';

ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS execution_started_at TIMESTAMPTZ;

ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS execution_finished_at TIMESTAMPTZ;