ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS commit_hash VARCHAR(64);

ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ;

ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS cleanup_warning TEXT;