ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS review_feedback TEXT;

ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS rejected_at TIMESTAMPTZ;

ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS correction_count INTEGER
NOT NULL DEFAULT 0;